const collection = [
    // men
    [
        {
            id: 1,
            category: "Men",
            title: "Embrodary Kurta",
            description: "Comfortable and trendy t-shirt for everyday wear.",
            price: "₹3,350.00",
            image: "/assets/img/men/8.webp",
            color: 'red',
            rating: 3.8,
            reviews: 35,
            size: ["S", "M", "L"],
            quantity: 1
        },
        {
            id: 2,
            category: "Men",
            title: "Casual Shirt",
            description: "Comfortable and trendy t-shirt for everyday wear.",
            price: "₹759.00",
            image: "/assets/img/men/4.webp",
            color: 'red',
            rating: 4.1,
            reviews: 55,
            size: ["S", "M", "L"],
            quantity: 1
        },
        {
            id: 3,
            category: "Men",
            title: "Ethnic Kurta",
            description: "Comfortable and trendy t-shirt for everyday wear.",
            price: "₹2,999.00",
            image: "/assets/img/men/5.webp",
            color: 'yellow',
            rating: 3.9,
            reviews: 40,
            size: ["S", "M", "L", "XL", "2XL", "3XL"],
            quantity: 1
        },
        {
            id: 4,
            category: "Men",
            title: "Casual Shirt",
            description: "Sophisticated blazer perfect for formal occasions.",
            price: "₹669.00",
            image: "/assets/img/men/2.webp",
            color: 'green',
            rating: 4.2,
            reviews: 85,
            size: ["S", "M", "L", "XL", "2XL", "3XL"],
            quantity: 1
        },
        {
            id: 5,
            category: "Men",
            title: "Printed Kurta",
            description: "Comfortable and trendy t-shirt for everyday wear",
            price: "₹1,300.00",
            image: "/assets/img/men/3.webp",
            color: 'blue',
            rating: 4.0,
            reviews: 60,
            size: ["S", "M", "L", "XL", "2XL", "3XL"],
            quantity: 1
        },
        {
            id: 6,
            category: "Men",
            title: "Chicken Embrodary Kurta",
            description: "Comfortable and trendy t-shirt for everyday wear.",
            price: "₹3,350.00",
            image: "/assets/img/men/6.webp",
            color: 'blue',
            rating: 4.3,
            reviews: 70,
            size: ["S", "3XL"],
            quantity: 1
        },
        {
            id: 7,
            category: "Men",
            title: "Casual Shirt",
            description: "Comfortable and trendy t-shirt for everyday wear.",
            price: "₹840.00",
            image: "/assets/img/men/7.webp",
            color: 'green',
            rating: 4.0,
            reviews: 50,
            size: [ "XL", "2XL", "3XL"],
            quantity: 1
        },
        {
            id: 8,
            category: "Men",
            title: "Casual Shirt",
            description: "Stylish leather jacket for a bold look.",
            price: "₹400.00",
            image: "/assets/img/men/1.webp",
            color: 'red',
            rating: 4.5,
            reviews: 120,
            size: ["S", "M", "L"],
            quantity: 1
        },
    ],
    // women
    [
        {
            id: 7,
            category: "Women",
            title: "Golden Lehanga For Wedding",
            description: "Warm and stylish lehanga for the winter season.",
            price: "₹5,000.00",
            image: "/assets/img/women/7.webp",
            color: 'yellow',
            rating: 4.2,
            reviews: 55,
            size: ["S", "M", "L", "XL", "2XL", "3XL"],
            quantity: 1
        },
        {
            id: 8,
            category: "Women",
            title: "Casual Saree",
            description: "Glamorous Saree for parties and celebrations.",
            price: "₹4,100.00",
            image: "/assets/img/women/8.webp",
            color: 'red',
            rating: 4.6,
            reviews: 90,
            size: ["S", "M", "L", "XL", "2XL"],
            quantity: 1
        },
        {
            id: 6,
            category: "Women",
            title: "Zilikaa Gorgeous Saree",
            description: "Comfortable Saree for your wedding function.",
            price: "₹1,900.00",
            image: "/assets/img/women/6.webp",
            color: 'red',
            rating: 4.5,
            reviews: 70,
            size: ["S", "M", "L", "XL"],
            quantity: 1
        },
        {
            id: 1,
            category: "Women",
            title: "Black  Bell-Bottom Jeans",
            description: "Light and breezy Jeans perfect for summer outings.",
            price: "₹950.00",
            image: "/assets/img/women/1.webp",
            color: 'black',
            rating: 4.6,
            reviews: 110,
            size: ["S", "M"],
            quantity: 1
        },
        {
            id: 3,
            category: "Women",
            title: "Blue Bell-Bottom",
            description: "Comfortable and stylish top for daily wear.",
            price: "₹400.00",
            image: "/assets/img/women/3.webp",
            color: 'blue',
            rating: 4.3,
            reviews: 60,
            size: ["S", "2XL", "3XL"],
            quantity: 1
        },
        {
            id: 4,
            category: "Women",
            title: "Denim Jeans",
            description: "Trendy denim Jeans for a casual look.",
            price: "₹3,589.00",
            image: "/assets/img/women/4.webp",
            color: 'black',
            rating: 4.4,
            reviews: 80,
            size: ["S", "M", "L", "XL", "2XL", "3XL"],
            quantity: 1
        },
        {
            id: 5,
            category: "Women",
            title: "Lehanga Choli",
            description: "Beautiful Lehanga Choli for a chic appearance.",
            price: "₹5,999.00",
            image: "/assets/img/women/5.webp",
            color: 'red',
            rating: 4.1,
            reviews: 45,
            size: ["S", "M", "L", "XL", "2XL", "3XL"],
            quantity: 1
        },
        {
            id: 2,
            category: "Women",
            title: "Evening Jeans",
            description: "Elegant Jeans for formal evening events.",
            price: "₹2,999.00",
            image: "/assets/img/women/2.webp",
            color: 'blue',
            rating: 4.7,
            reviews: 95,
            size: ["S", "M", "L", "XL"],
            quantity: 1
        },

    ],
    // kids
    [
        {
            id: 1,
            category: "Kids",
            title: "Casual Dress",
            description: "Comfortable and stylish casual shirt ",
            price: "₹700.00",
            image: "/assets/img/kid/1.webp",
            color: 'white',
            rating: 4.3,
            reviews: 30,
            size: [ "M"],
            quantity: 1
        },
        {
            id: 2,
            category: "Kids",
            title: "Formal Suit",
            description: "Elegant formal suit perfect for special occasions.",
            price: "₹2,500.00",
            image: "/assets/img/kid/2.webp",
            color: 'black',
            rating: 4.6,
            reviews: 25,
            size: ["S"],
            quantity: 1
        },
        {
            id: 3,
            category: "Kids",
            title: "Denim Jacket",
            description: "Trendy denim jacket to elevate your casual look.",
            price: "₹650.00",
            image: "/assets/img/kid/3.webp",
            color: 'white',
            rating: 4.4,
            reviews: 20,
            size: ["S", "M"],
            quantity: 1
        },
    ],
    // electronic
    [
        {
            id: 1,
            category: "Electronics",
            title: "Canon DSLR Camra",
            description: "Latest Camra with cutting-edge technology.",
            price: "₹78,000.00",
            image: "/assets/img/electronics/1.webp",
            color: 'black',
            rating: 4.8,
            reviews: 200,
            quantity: 1
        },
        {
            id: 2,
            category: "Electronics",
            title: " HP Laptop",
            description: "High-performance laptop for work and gaming.",
            price: "₹59,000.00",
            image: "/assets/img/electronics/2.webp",
            color: 'white',
            rating: 4.7,
            reviews: 150,
            quantity: 1
        },
        {
            id: 3,
            category: "Electronics",
            title: "Nikon",
            description: "Professional-grade camera for stunning photography.",
            price: "₹2,25,000.00",
            image: "/assets/img/electronics/3.webp",
            color: 'black',
            rating: 4.4,
            reviews: 80,
            quantity: 1
        },
        {
            id: 4,
            category: "Electronics",
            title: "Samsung Galaxy A36 5G",
            description: "Stylish Camra with AI tracking features.",
            price: "₹26,900.00",
            image: "/assets/img/electronics/4.webp",
            color: 'white',
            rating: 4.3,
            reviews: 65,
            quantity: 1
        },
        {
            id: 5,
            category: "Electronics",
            title: "Gaming Console",
            description: "Next-gen gaming console for ultimate gaming experience.",
            price: "₹95,650.00",
            image: "/assets/img/electronics/5.webp",
            color: 'white',
            rating: 4.9,
            reviews: 170,
            quantity: 1
        },
        {
            id: 6,
            category: "Electronics",
            title: "Gojrej Air Conditioner",
            description: "Different Mood Color And Consuming Very Less Energy",
            price: "₹80,000.00",
            image: "/assets/img/electronics/6.webp",
            color: 'white',
            rating: 4.6,
            reviews: 90,
            quantity: 1
        },
        {
            id: 7,
            category: "Electronics",
            title: "Vivo K25 Pro",
            description: "Lightweight Smart Phone for work and entertainment.",
            price: "₹17,999.00",
            image: "/assets/img/electronics/7.webp",
            color: 'black',
            rating: 4.5,
            reviews: 75,
            quantity: 1
        },
        {
            id: 8,
            category: "Electronics",
            title: "OPPO K12x 5G",
            description: "Damage-Proof Armour Body and Ultra-Slim Design",
            price: "₹2,500.00",
            image: "/assets/img/electronics/8.webp",
            color: 'white',
            rating: 4.2,
            reviews: 60,
            quantity: 1
        },
    ],
    // furniture
    [
        {
            id: 1,
            category: "Furniture",
            title: "Ocean Green Modern Sofa",
            description: "Comfortable and stylish sofa for your living room.",
            price: "₹5,700.00",
            image: "/assets/img/furniture/1.webp",
            color: 'green',
            rating: 4.2,
            reviews: 40,
            quantity: 1
        },
        {
            id: 2,
            category: "Furniture",
            title: "Podcast Sofa",
            description: "Elegant sofa made from high-quality wood.",
            price: "₹3,600.00",
            image: "/assets/img/furniture/2.webp",
            color: 'black',
            rating: 4.5,
            reviews: 35,
            quantity: 1
        },
        {
            id: 3,
            category: "Furniture",
            title: "Office Sofa",
            description: "Ergonomic office sofa for maximum comfort.",
            price: "₹2,100.00",
            image: "/assets/img/furniture/3.webp",
            color: 'yellow',
            rating: 4.1,
            reviews: 28,
            quantity: 1
        },
    ]
]
export default collection;
